### ISSUE TITLE
Issue creating a new language

### ISSUE THREAD

**Issue by dcastrili** [laravel-enso/DataTable#11]
I got an exception after creating a new locale "DataTables language file is missing for $locale". This issue is affecting the datatable rendering. I can see that the file is missing on the folder "dt-lang", but the record is created on the table language.

*vendor/laravel-enso/datatable/src/app/Classes/TableInit.php*

**Comment by aocneanu** [comment]
Not it takes the default lang file in case there is no dedicated one. Tell me what language you need and I will add it to the lib.

**Comment by dcastrili** [comment]
I need to add Spanish and later will add other languages.

**Comment by aocneanu** [comment]
There is no mechanism implemented for creating dt-lang files. To find out more about dt-lang files check:

https://github.com/DataTables/Plugins/tree/master/i18n
and
https://datatables.net/plug-ins/i18n/

If we need more files we will add them manually. In the future you can add lang files yourself, just make a PR ;)

To see how you can add a file check https://github.com/laravel-enso/Core/commit/c0848461d78bc246f27e987d06d7a8361c7b161d

Don't forget to run `composer update`, `php artisan vendor:publish` and select the `datatables-lang` tag to get the spanish lang file published from core.

Cheers

**Comment by dcastrili** [comment]
Ok, I got it. Thanks!
