### ISSUE TITLE
Build a datatable based on a third party json api resquest (Feature)

### ISSUE THREAD

**Issue by dcastrili** [laravel-enso/DataTable#12]
Hi,

Will be very useful to allow not only pass a raw query to this package else to be able to pass a json, in order to load data from external api integration (mailchimp, github, and so on).

That will give to this package a powerful integration with the enso admin-panel.

I did a test with a rest api that I have developed. It worked, if I overwrite the method ```public function getTableData()``` on the ```trait use LaravelEnso\DataTable\app\Traits\DataTable;```

```tableController.php```

```php
public function getTableData()
    {
        $client = new Client(['base_uri' => env('API_HOST')]);

        $ApiAuthorization = ['headers' => [
            'X-Authorization'=> 'xxxxxxxx'
        ], 'http_errors' => true];

        $response = $client->request('GET', 'my-endpoint', $ApiAuthorization);
       
        // The response already contains the fields needed for the package to create the table. The 
        // response return exactly the same as the raw query does. 
        return response()->json(json_decode($response->getBody()));
    }
```

Something did not worked for me when I tested it passing a filter for search. I tried to return exactly what was expected but I realised I was missing something else. I have not try any further but seems like its possible to integrate it.

Regarding to search some challenges will show up for sure, since there is no sql at all. But maybe could be fixed by filtering array of collections and using transformers for formating the right json response.

**Comment by aocneanu** [comment]
Hi,

This is something that is on our mind since forever, and will be implemented in the near future ( #2 ).

We delayed it because the API needs a complete refactor, but soon it will be done.

We are taking in consideration to give up DataTables library and build something 100% on Vue.

Cheers,

**Comment by dcastrili** [comment]
Yes! 

That makes sense. I had used a Vue.js table component that worked fine for me with server side, but outside of enso.

Cheers

**Comment by aocneanu** [comment]
Replaced with https://github.com/laravel-enso/vuedatatable
