### ISSUE TITLE
How to Implement Search bar

### ISSUE THREAD

**Issue by naishu** [laravel-enso/DataTable#17]
Hi 
I have implemented the data table. Also have added the meta tag "searchable" for the columns. but the search box doesn't appear. I checked the documentation and couldn't find anything related to search bar . 

The following is my template.json file . Please let me know what i'm missing here so that i can enable the search bar on top on the table as shown in the examples.

```
{
   "routePrefix": "table",
    

    "crtNo": true,
    "cache": false,
    "flatten": false,
    "auth": false,
    "debounce": 100,
    "lengthMenu": [10, 15, 20, 25, 30],
     "selectable": false,

    "comparisonOperator": "LIKE",
       "columns": [
        {
            "label": "name",
            "data": "table.name",
            "name": "name",
            "meta": ["searchable", "sortable"]
       }
]
}
           
```

**Comment by aocneanu** [comment]
The searchbar is there by default, if you have at least one searchable field. You will find ~ 10 examples of tables in Enso's codebase, including an example package

**Comment by naishu** [comment]
There is a searchable field, for the column. 
 "meta": ["searchable", "sortable"]
but some reason it does not appear. all other buttons  like refresh,reload appears. I can post a screenshot .

**Comment by naishu** [comment]
@aocneanu  I think  i posted in the wrong repository . I'm using the VueData table!

**Comment by aocneanu** [comment]
Open a new ticket in the right repo and post a pic too.

Don't forget to check the console for any errors
